version: "3.7"

services:
  web:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    command: >
      sh -c "python3 ./manage.py migrate &&
             gunicorn config.wsgi:application -b 0.0.0.0:4000"
    env_file:
      - ./.env