# Generated by Django 4.1 on 2024-06-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_portal', '0002_apirequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apirequest',
            name='path',
        ),
        migrations.RemoveField(
            model_name='apirequest',
            name='user',
        ),
    ]
